### ISSUE TITLE
present categories as browsable collections / anthologies

### ISSUE THREAD

**Issue by flashashen** [flashashen/zombiepoetryproject#26]
submissions are being organized via categories so they can be viewed under different collections or anthologies. Find a way to present these so they can be browsed by users

**Comment by flashashen** [comment]
first cut of this is live. It uses standard wp capability to setup a menu of categories. It's a simple setup that I got from https://wptavern.com/how-to-create-a-dropdown-menu-of-wordpress-categories-without-using-code.

A standard post template is used for the submissions which means that users see an excerpt of the victim text and when the click on 'continue' they see the familar two-column victim / zombie layout. 

it actually looks good for a 10 minute solution. awaiting comment from the progenitor and lord of this project..

**Comment by multiverse15** [comment]
I like the set up of this a lot. There seem to be a couple of little oddities that are most likely user error, but I can;t figure out what I'm doing wrong. The anthologies tab doesn't replicate the victim text, which is actually fine, but when I remove the Incidents category in a few cases it doesn't seem to take and so the posts are still on the Incidents page, but without the victim texts, which looks odd. Otherwise, it's all organized well!

**Comment by flashashen** [comment]
committed a fix for incidents page and also a fix for anthologies page. category based curation i believe working as intended now.

**Comment by multiverse15** [comment]
This is excellent and suggests such elegance of mind! Such refinement!
